/** Development-only fallback records; every non-confirmed record is visibly tagged as sample content. */
export const demoPlayers = [
  { id: "fakhar-zaman", fullName: "Fakhar Zaman", displayName: "Fakhar Zaman", shortName: "Fakhar", slug: "fakhar-zaman", country: "Pakistan", nationality: "Pakistan", role: null, jerseyNumber: null, profileImage: null, coverImage: null, bio: null, battingStyle: null, bowlingStyle: null, heightCm: null, dateOfBirth: null, isCaptain: false, isViceCaptain: false, isIconPlayer: true, isActive: true, isDemo: false, displayOrder: 1 },
  { id: "iftikhar-ahmed", fullName: "Iftikhar Ahmed", displayName: null, shortName: null, slug: "iftikhar-ahmed", country: null, nationality: null, role: null, jerseyNumber: null, profileImage: null, coverImage: null, bio: null, battingStyle: null, bowlingStyle: null, heightCm: null, dateOfBirth: null, isCaptain: false, isViceCaptain: false, isIconPlayer: false, isActive: true, isDemo: false, displayOrder: 2 },
  { id: "faheem-ashraf", fullName: "Faheem Ashraf", displayName: null, shortName: null, slug: "faheem-ashraf", country: null, nationality: null, role: null, jerseyNumber: null, profileImage: null, coverImage: null, bio: null, battingStyle: null, bowlingStyle: null, heightCm: null, dateOfBirth: null, isCaptain: false, isViceCaptain: false, isIconPlayer: false, isActive: true, isDemo: false, displayOrder: 3 },
  { id: "azmatullah-omarzai", fullName: "Azmatullah Omarzai", displayName: null, shortName: null, slug: "azmatullah-omarzai", country: null, nationality: null, role: null, jerseyNumber: null, profileImage: null, coverImage: null, bio: null, battingStyle: null, bowlingStyle: null, heightCm: null, dateOfBirth: null, isCaptain: false, isViceCaptain: false, isIconPlayer: false, isActive: true, isDemo: false, displayOrder: 4 },
  { id: "abbas-afridi", fullName: "Abbas Afridi", displayName: null, shortName: null, slug: "abbas-afridi", country: null, nationality: null, role: null, jerseyNumber: null, profileImage: null, coverImage: null, bio: null, battingStyle: null, bowlingStyle: null, heightCm: null, dateOfBirth: null, isCaptain: false, isViceCaptain: false, isIconPlayer: false, isActive: true, isDemo: false, displayOrder: 5 },
  { id: "odean-smith", fullName: "Odean Smith", displayName: null, shortName: null, slug: "odean-smith", country: null, nationality: null, role: null, jerseyNumber: null, profileImage: null, coverImage: null, bio: null, battingStyle: null, bowlingStyle: null, heightCm: null, dateOfBirth: null, isCaptain: false, isViceCaptain: false, isIconPlayer: false, isActive: true, isDemo: false, displayOrder: 6 },
  { id: "nurul-hasan", fullName: "Nurul Hasan", displayName: null, shortName: null, slug: "nurul-hasan", country: null, nationality: null, role: null, jerseyNumber: null, profileImage: null, coverImage: null, bio: null, battingStyle: null, bowlingStyle: null, heightCm: null, dateOfBirth: null, isCaptain: false, isViceCaptain: false, isIconPlayer: false, isActive: true, isDemo: false, displayOrder: 7 },
  { id: "paul-van-meekeren", fullName: "Paul van Meekeren", displayName: null, shortName: null, slug: "paul-van-meekeren", country: null, nationality: null, role: null, jerseyNumber: null, profileImage: null, coverImage: null, bio: null, battingStyle: null, bowlingStyle: null, heightCm: null, dateOfBirth: null, isCaptain: false, isViceCaptain: false, isIconPlayer: false, isActive: true, isDemo: false, displayOrder: 8 },
  { id: "adithya-shetty", fullName: "Adithya Shetty", displayName: null, shortName: null, slug: "adithya-shetty", country: null, nationality: null, role: null, jerseyNumber: null, profileImage: null, coverImage: null, bio: null, battingStyle: null, bowlingStyle: null, heightCm: null, dateOfBirth: null, isCaptain: false, isViceCaptain: false, isIconPlayer: false, isActive: true, isDemo: false, displayOrder: 9 },
];

export const sampleNews = [
  { id: "sample-news-1", title: "Inside the Tigers: a season of firsts", slug: "inside-the-tigers-sample", excerpt: "A sample story layout for the United Tigers newsroom. Replace this copy with an approved club announcement.", content: "Sample newsroom content. Use the admin panel to replace this draft with approved franchise news.", category: "TEAM NEWS", coverImage: null, ogImage: null, seoTitle: null, seoDescription: null, authorName: "United Tigers", publishedAt: new Date("2026-10-01T12:00:00Z"), isFeatured: true, isDemo: true },
  { id: "sample-news-2", title: "The fast format, up close", slug: "fast-format-sample", excerpt: "A sample editorial card showing how match reports and team features will appear.", content: "Sample newsroom content. Use the admin panel to replace this draft with approved franchise news.", category: "FEATURE", coverImage: null, ogImage: null, seoTitle: null, seoDescription: null, authorName: "United Tigers", publishedAt: new Date("2026-09-28T12:00:00Z"), isFeatured: false, isDemo: true },
];

export const sampleUpdates = [
  { id: "sample-update-1", title: "Welcome to the Tigers’ digital home", slug: "welcome-sample", description: "This is sample content. The team can post training, travel, match-day and community updates here.", content: null, category: "ANNOUNCEMENT", image: null, video: null, publishedAt: new Date("2026-10-01T15:00:00Z"), isFeatured: true, isPublished: true, isDemo: true, player: null },
  { id: "sample-update-2", title: "A place for every moment", slug: "moments-sample", description: "Daily updates will appear here when the club publishes them through the CMS.", content: null, category: "BEHIND_THE_SCENES", image: null, video: null, publishedAt: new Date("2026-09-30T14:15:00Z"), isFeatured: false, isPublished: true, isDemo: true, player: null },
];

