"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Check, Edit3, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import { EmptyState } from "@/components/EmptyState";
import { RichTextEditor } from "@/components/RichTextEditor";

type Entry = Record<string, unknown> & { id: string };
type Field = { key: string; label: string; type?: "text" | "password" | "textarea" | "richtext" | "url" | "date" | "select" | "checkbox" | "number" | "file"; options?: string[]; required?: boolean; hint?: string; accept?: string };
const config: Record<string, { title: string; subtitle: string; fields?: Field[]; columns: [string, string][]; create?: boolean; edit?: boolean; remove?: boolean }> = {
  players: { title: "Players", subtitle: "Edit player profiles, squad details and availability.", create: true, edit: true, remove: true, columns: [["fullName", "PLAYER"], ["role", "ROLE"], ["nationality", "NATIONALITY"], ["isIconPlayer", "ICON"], ["isActive", "STATUS"]], fields: [
    { key: "fullName", label: "Full name", required: true }, { key: "displayName", label: "Display name" }, { key: "country", label: "Country" }, { key: "nationality", label: "Nationality" }, { key: "role", label: "Playing role", type: "select", options: ["", "BATTER", "BOWLER", "ALL_ROUNDER", "WICKETKEEPER"] }, { key: "jerseyNumber", label: "Squad number", type: "number" }, { key: "profileImage", label: "Profile image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "coverImage", label: "Cover image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "bio", label: "Biography", type: "textarea" }, { key: "isIconPlayer", label: "Icon player", type: "checkbox" }, { key: "isCaptain", label: "Captain", type: "checkbox" }, { key: "isViceCaptain", label: "Vice captain", type: "checkbox" }, { key: "isActive", label: "Active", type: "checkbox" }, { key: "displayOrder", label: "Display order", type: "number" },
  ] },
  staff: { title: "Coaching & staff", subtitle: "Manage coaching, support staff and club leadership profiles.", create: true, edit: true, remove: true, columns: [["fullName", "NAME"], ["title", "TITLE"], ["category", "AREA"], ["isActive", "STATUS"]], fields: [{ key: "fullName", label: "Full name", required: true }, { key: "title", label: "Role or title", required: true }, { key: "category", label: "Team area", type: "select", options: ["COACHING", "SUPPORT", "MANAGEMENT"] }, { key: "profileImage", label: "Profile image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "bio", label: "Biography", type: "textarea" }, { key: "displayOrder", label: "Display order", type: "number" }, { key: "isActive", label: "Active", type: "checkbox" }] },
  news: { title: "Newsroom", subtitle: "Write, edit and publish news stories and announcements.", create: true, edit: true, remove: true, columns: [["title", "STORY"], ["category", "CATEGORY"], ["status", "STATUS"], ["isFeatured", "FEATURED"], ["updatedAt", "UPDATED"]], fields: [
    { key: "title", label: "Title", required: true }, { key: "excerpt", label: "Excerpt", type: "textarea", required: true }, { key: "category", label: "Category", required: true }, { key: "authorName", label: "Author" }, { key: "coverImage", label: "Cover image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "content", label: "Story content", type: "richtext", required: true }, { key: "seoTitle", label: "SEO title" }, { key: "seoDescription", label: "SEO description", type: "textarea" }, { key: "status", label: "Publishing status", type: "select", options: ["DRAFT", "PUBLISHED", "SCHEDULED"] }, { key: "publishedAt", label: "Publish date", type: "date" }, { key: "isFeatured", label: "Featured article", type: "checkbox" },
  ] },
  updates: { title: "Tigers Daily", subtitle: "Post training notes, team news and behind-the-scenes moments.", create: true, edit: true, remove: true, columns: [["title", "UPDATE"], ["category", "CATEGORY"], ["isPublished", "PUBLISHED"], ["publishedAt", "DATE"]], fields: [
    { key: "title", label: "Title", required: true }, { key: "description", label: "Short description", type: "textarea", required: true }, { key: "category", label: "Category", type: "select", options: ["TRAINING", "MATCH_DAY", "TEAM_NEWS", "PLAYER_NEWS", "ANNOUNCEMENT", "BEHIND_THE_SCENES", "MEDIA", "TRAVEL", "COMMUNITY"] }, { key: "image", label: "Image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "video", label: "Video", type: "file", accept: "video/mp4" }, { key: "content", label: "Full update", type: "richtext" }, { key: "publishedAt", label: "Publish date", type: "date", required: true }, { key: "isFeatured", label: "Featured", type: "checkbox" }, { key: "isPublished", label: "Published", type: "checkbox" },
  ] },
  matches: { title: "Fixtures & matches", subtitle: "Manage official fixtures, match status and result information.", create: true, edit: true, remove: true, columns: [["opponent", "OPPONENT"], ["date", "DATE"], ["status", "STATUS"], ["venue", "VENUE"], ["competition", "COMPETITION"]], fields: [
    { key: "opponent", label: "Opponent", required: true }, { key: "date", label: "Date and time", type: "date", required: true }, { key: "status", label: "Status", type: "select", options: ["UPCOMING", "LIVE", "COMPLETED", "POSTPONED", "CANCELLED"] }, { key: "competition", label: "Competition" }, { key: "matchNumber", label: "Match number" }, { key: "venueName", label: "Venue" }, { key: "result", label: "Result", type: "textarea" },
  ] },
  gallery: { title: "Media library", subtitle: "Curate photos and videos for the public gallery.", create: true, edit: false, remove: true, columns: [["title", "TITLE"], ["category", "CATEGORY"], ["type", "TYPE"], ["isPublished", "PUBLISHED"]], fields: [{ key: "title", label: "Title", required: true }, { key: "category", label: "Category", required: true }, { key: "mediaUrl", label: "Upload media", type: "file", accept: "image/jpeg,image/png,image/webp,video/mp4", required: true, hint: "JPG, PNG, WebP or MP4 · max 25 MB" }, { key: "type", label: "Type", type: "select", options: ["IMAGE", "VIDEO"] }, { key: "altText", label: "Alt text" }, { key: "displayOrder", label: "Display order", type: "number" }, { key: "isPublished", label: "Published", type: "checkbox" }] },
  sponsors: { title: "Partners", subtitle: "Manage sponsor names, logos and display order.", create: true, edit: false, remove: true, columns: [["name", "PARTNER"], ["category", "TIER"], ["website", "WEBSITE"], ["isPublished", "PUBLISHED"]], fields: [{ key: "name", label: "Partner name", required: true }, { key: "category", label: "Partner category", required: true }, { key: "logoUrl", label: "Logo URL", type: "url" }, { key: "website", label: "Website", type: "url" }, { key: "displayOrder", label: "Display order", type: "number" }, { key: "isPublished", label: "Published", type: "checkbox" }] },
  contacts: { title: "Contact messages", subtitle: "Review supporter, partnership and media enquiries.", columns: [["name", "SENDER"], ["email", "EMAIL"], ["subject", "SUBJECT"], ["isRead", "STATUS"], ["createdAt", "RECEIVED"]] },
  records: { title: "Statistics & records", subtitle: "Performance data is calculated from match scorecards. Verified record cards can be managed here.", columns: [["title", "RECORD"], ["value", "VALUE"], ["scope", "SCOPE"], ["playerName", "PLAYER"], ["seasonYear", "SEASON"]] },
  settings: { title: "Website settings", subtitle: "Control homepage messaging and public site settings.", create: true, columns: [["key", "SETTING"], ["value", "VALUE"], ["updatedAt", "UPDATED"]], fields: [{ key: "key", label: "Setting key", required: true }, { key: "value", label: "Value (plain text or JSON)", type: "textarea", required: true }] },
  audit: { title: "Audit log", subtitle: "A traceable history of important administrator actions.", columns: [["action", "ACTION"], ["entity", "SECTION"], ["entityId", "RECORD"], ["user", "ADMIN"], ["createdAt", "TIME"]] },
  users: { title: "Admin users", subtitle: "Create administrator accounts and assign a built-in access role.", create: true, edit: true, remove: true, columns: [["name", "NAME"], ["email", "EMAIL"], ["role", "ROLE"], ["isActive", "ACTIVE"], ["lastLoginAt", "LAST SIGN-IN"]], fields: [{ key: "name", label: "Full name", required: true }, { key: "email", label: "Email address", type: "text", required: true }, { key: "role", label: "Access role", type: "select", options: ["SUPER_ADMIN", "ADMIN", "EDITOR", "STATISTICS_MANAGER", "CONTENT_MANAGER"], required: true }, { key: "password", label: "Temporary password", type: "password", required: true, hint: "At least 12 characters. Leave blank when editing to keep the current password." }, { key: "isActive", label: "Active account", type: "checkbox" }] },
  roles: { title: "Roles & permissions", subtitle: "Built-in roles use a fixed permission matrix enforced by every API route.", columns: [["name", "ROLE"], ["description", "ACCESS SUMMARY"], ["permissions", "PERMISSIONS"]] },
};
const showValue = (value: unknown) => value == null || value === "" ? "—" : typeof value === "boolean" ? value ? "YES" : "NO" : typeof value === "object" ? JSON.stringify(value) : String(value);
const inputDate = (value: unknown) => { if (!value) return ""; const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 16); };

export function AdminWorkspace({ section }: { section: string }) {
  const definition = config[section]; const [items, setItems] = useState<Entry[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [query, setQuery] = useState(""); const [editor, setEditor] = useState(false); const [active, setActive] = useState<Entry | null>(null); const [form, setForm] = useState<Record<string, string | boolean>>({}); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setNotice("");
    try { const response = await fetch(`/api/v1/admin/${section}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Could not load this section."); setItems(Array.isArray(result.data) ? result.data : []); if (result.message?.includes("Database is not connected")) setError(result.message); else setError(""); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load this section."); setItems([]); } finally { setLoading(false); }
  }, [section]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => items.filter((item) => JSON.stringify(item).toLowerCase().includes(query.toLowerCase())), [items, query]);
  if (!definition) return <div className="admin-content"><div className="admin-page-heading"><div><h1>Section unavailable</h1><p>This CMS section doesn’t exist.</p></div></div></div>;
  function startCreate() { const values: Record<string, string | boolean> = {}; for (const field of definition.fields ?? []) values[field.key] = field.type === "checkbox" ? ["isActive", "isPublished"].includes(field.key) : field.type === "select" ? (field.options?.[0] === "" ? "" : field.options?.[0] ?? "") : field.key === "publishedAt" || field.key === "date" ? inputDate(new Date()) : ""; setForm(values); setActive(null); setEditor(true); setError(""); setNotice(""); }
  function startEdit(item: Entry) { const values: Record<string, string | boolean> = {}; for (const field of definition.fields ?? []) { const value = item[field.key]; values[field.key] = field.type === "checkbox" ? Boolean(value) : field.type === "date" ? inputDate(value) : value == null ? "" : String(value); } setForm(values); setActive(item); setEditor(true); setError(""); setNotice(""); }
  function change(key: string, value: string | boolean) { setForm((current) => ({ ...current, [key]: value })); }
  async function uploadFile(field: Field, file?: File) {
    if (!file) return;
    setUploading(true); setError(""); setNotice("");
    const upload = new FormData(); upload.append("file", file); upload.append("folder", section);
    try { const response = await fetch("/api/v1/admin/media/upload", { method: "POST", body: upload }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Upload failed."); change(field.key, result.data.url); if (section === "gallery") change("type", file.type === "video/mp4" ? "VIDEO" : "IMAGE"); setNotice(`${file.name} uploaded and attached.`); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed."); }
    finally { setUploading(false); }
  }
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setNotice("");
    const body: Record<string, unknown> = { ...form };
    for (const field of definition.fields ?? []) {
      if (field.type === "checkbox") body[field.key] = Boolean(form[field.key]);
      if (field.type === "number") body[field.key] = form[field.key] === "" ? null : Number(form[field.key]);
      if (field.type === "date" && form[field.key]) body[field.key] = new Date(String(form[field.key])).toISOString();
      if (["url"].includes(field.type || "") && form[field.key] === "") body[field.key] = null;
      if (field.type === "select" && form[field.key] === "") body[field.key] = null;
    }
    if (section === "users" && active && body.password === "") delete body.password;
    if (section === "settings" && typeof body.value === "string") { try { body.value = JSON.parse(body.value); } catch { /* plain-text setting */ } }
    try { const response = await fetch(`/api/v1/admin/${section}${active ? `/${active.id}` : ""}`, { method: active ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Could not save this record."); setNotice(active ? "Changes saved." : "Record created."); setEditor(false); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save this record."); }
  }
  async function deactivate(item: Entry) {
    if (!window.confirm(`Deactivate “${String(item.title ?? item.fullName ?? item.name ?? item.opponent ?? "this record")}”?`)) return;
    try { const response = await fetch(`/api/v1/admin/${section}/${item.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setNotice("Record deactivated."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not deactivate this record."); }
  }
  async function markRead(item: Entry) { try { const response = await fetch(`/api/v1/admin/${section}/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ isRead: true }) }); if (!response.ok) throw new Error("Could not mark message as read."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update message."); } }
  return <div className="admin-content"><div className="admin-page-heading"><div><span className="eyebrow"><i className="eyebrow-dot" />UNITED TIGERS CMS</span><h1>{definition.title}</h1><p>{definition.subtitle}</p></div><button className="admin-secondary-btn" onClick={() => void load()}><RefreshCw size={13} /> Refresh</button></div>
    {error && <div className="admin-demo-alert"><AlertTriangle size={14} />{error}</div>}{notice && <p className="admin-notice"><Check size={13} /> {notice}</p>}
    {editor && definition.fields && <form className="admin-editor" onSubmit={save}><div className="admin-panel-header"><h2>{active ? "Edit record" : "Create record"}</h2><button type="button" className="icon-button" onClick={() => setEditor(false)} aria-label="Close editor"><X size={16} /></button></div><div className="admin-editor-grid">{definition.fields.map((field) => <label key={field.key} className={field.type === "textarea" || field.type === "richtext" ? "field-wide" : ""}>{field.type === "checkbox" ? <span className="admin-check-label"><input type="checkbox" checked={Boolean(form[field.key])} onChange={(event) => change(field.key, event.target.checked)} />{field.label}</span> : <>{field.label}{field.type === "richtext" ? <RichTextEditor required={field.required} value={String(form[field.key] ?? "")} onChange={(value) => change(field.key, value)} /> : field.type === "textarea" ? <textarea required={field.required} value={String(form[field.key] ?? "")} onChange={(event) => change(field.key, event.target.value)} /> : field.type === "select" ? <select required={field.required} value={String(form[field.key] ?? "")} onChange={(event) => change(field.key, event.target.value)}>{field.options?.map((option) => <option value={option} key={option}>{option || "Select"}</option>)}</select> : field.type === "file" ? <><input type="file" accept={field.accept} required={field.required && !form[field.key]} onChange={(event) => void uploadFile(field, event.currentTarget.files?.[0])} />{form[field.key] && <small className="uploaded-file">ATTACHED: {String(form[field.key])}</small>}{uploading && <small>UPLOADING…</small>}</> : <input type={field.type === "date" ? "datetime-local" : field.type === "number" ? "number" : field.type === "url" ? "url" : field.type === "password" ? "password" : "text"} required={field.key === "password" ? !active : field.required} value={String(form[field.key] ?? "")} onChange={(event) => change(field.key, event.target.value)} autoComplete={field.type === "password" ? "new-password" : undefined} />}{field.hint && <small>{field.hint}</small>}</>}</label>)}</div><div className="admin-editor-actions"><button type="button" className="admin-secondary-btn" onClick={() => setEditor(false)}>Cancel</button><button className="admin-primary-btn" type="submit" disabled={uploading}>{active ? "SAVE CHANGES" : "CREATE RECORD"}</button></div></form>}
    <div className="admin-toolbar"><label className="admin-search-wrap"><Search size={14} /><input className="admin-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${definition.title.toLowerCase()}`} /></label>{definition.create && <button className="admin-primary-btn" onClick={startCreate}><Plus size={14} /> CREATE NEW</button>}</div>
    {loading ? <div className="admin-table-wrap"><div className="admin-loading-inline"><span className="admin-spinner" /> LOADING RECORDS</div></div> : visible.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{definition.columns.map(([key, label]) => <th key={key}>{label}</th>)}{(definition.edit || definition.remove || section === "contacts" || section === "matches") && <th>ACTIONS</th>}</tr></thead><tbody>{visible.map((item) => <tr key={item.id}>{definition.columns.map(([key]) => <td key={key}><strong>{key === "user" ? String((item.user as { email?: string } | null)?.email || "Admin") : key === "venue" ? String((item.venue as { name?: string } | null)?.name || "—") : showValue(item[key])}</strong></td>)}{(definition.edit || definition.remove || section === "contacts" || section === "matches") && <td className="row-actions">{section === "matches" && <Link href={`/admin/matches/${item.id}/scorecard`}>SCORECARD</Link>}{definition.edit && <button onClick={() => startEdit(item)}><Edit3 size={12} /> EDIT</button>}{section === "contacts" && !item.isRead && <button onClick={() => void markRead(item)}><Check size={12} /> MARK READ</button>}{definition.remove && <button className="danger-text" onClick={() => void deactivate(item)}><Trash2 size={12} /> DEACTIVATE</button>}</td>}</tr>)}</tbody></table></div> : !error ? <EmptyState title={query ? "No matching records" : "Nothing here yet"} description={query ? "Adjust the search and try again." : section === "matches" ? "Create the first verified match record when the schedule is confirmed." : "New records will appear here when added through the CMS."} /> : null}
    {section === "gallery" && <p className="admin-storage-note">Uploads use the configured S3-compatible storage provider. Set the storage credentials in the server environment before adding media.</p>}
  </div>;
}

