"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Check, Edit3, Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { EmptyState } from "@/components/EmptyState";
import { SiteSettingsPanel } from "@/components/SiteSettingsPanel";

type Entry = Record<string, unknown> & { id: string };
export type Field = { key: string; label: string; type?: "text" | "password" | "textarea" | "richtext" | "url" | "date" | "day" | "select" | "checkbox" | "number" | "file"; options?: string[]; required?: boolean; hint?: string; accept?: string };
export const adminSections: Record<string, { title: string; subtitle: string; fields?: Field[]; columns: [string, string][]; create?: boolean; edit?: boolean; remove?: boolean }> = {
  players: { title: "Players", subtitle: "Edit player profiles, squad details and availability.", create: true, edit: true, remove: true, columns: [["fullName", "PLAYER"], ["role", "ROLE"], ["nationality", "NATIONALITY"], ["isIconPlayer", "ICON"], ["isActive", "STATUS"]], fields: [
    { key: "fullName", label: "Full name", required: true }, { key: "displayName", label: "Display name", hint: "Shown on the squad card and profile heading." }, { key: "shortName", label: "Short name" }, { key: "slug", label: "Profile address", hint: "Public page address, for example fakhar-zaman. Leave blank to build it from the full name." }, { key: "country", label: "Country" }, { key: "nationality", label: "Nationality" }, { key: "dateOfBirth", label: "Date of birth", type: "day" }, { key: "role", label: "Playing role", type: "select", options: ["", "BATTER", "BOWLER", "ALL_ROUNDER", "WICKETKEEPER"] }, { key: "battingStyle", label: "Batting style" }, { key: "bowlingStyle", label: "Bowling style" }, { key: "heightCm", label: "Height (cm)", type: "number" }, { key: "jerseyNumber", label: "Squad number", type: "number" }, { key: "profileImage", label: "Profile image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "coverImage", label: "Cover image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "bio", label: "Biography", type: "textarea" }, { key: "isIconPlayer", label: "Icon player", type: "checkbox" }, { key: "isCaptain", label: "Captain", type: "checkbox" }, { key: "isViceCaptain", label: "Vice captain", type: "checkbox" }, { key: "isActive", label: "Show on website", type: "checkbox" }, { key: "displayOrder", label: "Display order", type: "number" },
  ] },
  staff: { title: "Coaching & staff", subtitle: "Manage coaching, support staff and club leadership profiles.", create: true, edit: true, remove: true, columns: [["fullName", "NAME"], ["title", "TITLE"], ["category", "AREA"], ["isActive", "STATUS"]], fields: [{ key: "fullName", label: "Full name", required: true }, { key: "title", label: "Role or title", required: true, hint: "Shown under the name on the squad page." }, { key: "category", label: "Team area", type: "select", options: ["COACHING", "SUPPORT", "MANAGEMENT"], required: true }, { key: "profileImage", label: "Profile image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "bio", label: "Biography", type: "textarea", hint: "Shown on the staff card." }, { key: "displayOrder", label: "Display order", type: "number" }, { key: "isActive", label: "Show on website", type: "checkbox" }] },
  news: { title: "Newsroom", subtitle: "Write, edit and publish news stories and announcements.", create: true, edit: true, remove: true, columns: [["title", "STORY"], ["category", "CATEGORY"], ["status", "STATUS"], ["isFeatured", "FEATURED"], ["updatedAt", "UPDATED"]], fields: [
    { key: "title", label: "Title", required: true }, { key: "excerpt", label: "Excerpt", type: "textarea", required: true }, { key: "category", label: "Category", required: true }, { key: "authorName", label: "Author" }, { key: "coverImage", label: "Cover image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "content", label: "Story content", type: "richtext", required: true }, { key: "seoTitle", label: "SEO title" }, { key: "seoDescription", label: "SEO description", type: "textarea" }, { key: "status", label: "Publishing status", type: "select", options: ["DRAFT", "PUBLISHED", "SCHEDULED"] }, { key: "publishedAt", label: "Publish date", type: "date" }, { key: "isFeatured", label: "Featured article", type: "checkbox" },
  ] },
  updates: { title: "Tigers Daily", subtitle: "Post training notes, team news and behind-the-scenes moments.", create: true, edit: true, remove: true, columns: [["title", "UPDATE"], ["category", "CATEGORY"], ["isPublished", "PUBLISHED"], ["publishedAt", "DATE"]], fields: [
    { key: "title", label: "Title", required: true }, { key: "description", label: "Short description", type: "textarea", required: true }, { key: "category", label: "Category", type: "select", options: ["TRAINING", "MATCH_DAY", "TEAM_NEWS", "PLAYER_NEWS", "ANNOUNCEMENT", "BEHIND_THE_SCENES", "MEDIA", "TRAVEL", "COMMUNITY"] }, { key: "image", label: "Image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "video", label: "Video", type: "file", accept: "video/mp4" }, { key: "content", label: "Full update", type: "richtext" }, { key: "publishedAt", label: "Publish date", type: "date", required: true }, { key: "isFeatured", label: "Featured", type: "checkbox" }, { key: "isPublished", label: "Published", type: "checkbox" },
  ] },
  matches: { title: "Fixtures & matches", subtitle: "Manage official fixtures, match status and result information.", create: true, edit: true, remove: true, columns: [["opponent", "OPPONENT"], ["date", "DATE"], ["status", "STATUS"], ["venue", "VENUE"], ["competition", "COMPETITION"]], fields: [
    { key: "opponent", label: "Opponent", required: true }, { key: "date", label: "Date and time", type: "date", required: true }, { key: "status", label: "Status", type: "select", options: ["UPCOMING", "LIVE", "COMPLETED", "POSTPONED", "CANCELLED"] }, { key: "competition", label: "Competition" }, { key: "matchNumber", label: "Match number" }, { key: "venueName", label: "Venue" }, { key: "result", label: "Result", type: "textarea" },
  ] },
  gallery: { title: "Media library", subtitle: "Curate photos and videos for the public gallery.", create: true, edit: true, remove: true, columns: [["title", "TITLE"], ["category", "CATEGORY"], ["type", "TYPE"], ["isFeatured", "FEATURED"], ["isPublished", "PUBLISHED"]], fields: [{ key: "title", label: "Title", required: true }, { key: "category", label: "Category", required: true }, { key: "mediaUrl", label: "Upload media", type: "file", accept: "image/jpeg,image/png,image/webp,video/mp4", required: true, hint: "JPG, PNG, WebP or MP4 · max 25 MB" }, { key: "type", label: "Type", type: "select", options: ["IMAGE", "VIDEO"] }, { key: "altText", label: "Alt text" }, { key: "displayOrder", label: "Display order", type: "number" }, { key: "isFeatured", label: "Featured on the homepage", type: "checkbox" }, { key: "isPublished", label: "Published", type: "checkbox" }] },
  sponsors: { title: "Partners", subtitle: "Manage sponsor names, logos and display order.", create: true, edit: true, remove: true, columns: [["name", "PARTNER"], ["category", "TIER"], ["website", "WEBSITE"], ["isPublished", "PUBLISHED"]], fields: [{ key: "name", label: "Partner name", required: true }, { key: "category", label: "Partner category", required: true, hint: "Shown as the partner tier, for example TITLE or PRINCIPAL." }, { key: "logoUrl", label: "Logo", type: "file", accept: "image/jpeg,image/png,image/webp", hint: "Wide logo, JPG, PNG or WebP." }, { key: "website", label: "Website", type: "url" }, { key: "displayOrder", label: "Display order", type: "number" }, { key: "isPublished", label: "Show on website", type: "checkbox" }] },
  products: { title: "Merchandise", subtitle: "Kit and products fans can book. Add a colour and size for every version you sell.", create: true, edit: true, remove: true, columns: [["name", "PRODUCT"], ["category", "CATEGORY"], ["price", "PRICE"], ["variantCount", "VARIANTS"], ["isFeatured", "FEATURED"], ["isPublished", "LIVE"]], fields: [
    { key: "name", label: "Product name", required: true }, { key: "slug", label: "Shop address", hint: "Leave blank to build it from the name." }, { key: "category", label: "Category", type: "select", options: ["JERSEY", "TRAINING", "CAP", "ACCESSORY"], required: true }, { key: "price", label: "Price (AED)", type: "number", required: true }, { key: "image", label: "Main image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "description", label: "Description", type: "textarea", required: true }, { key: "isFeatured", label: "Featured on the homepage", type: "checkbox" }, { key: "isPublished", label: "Show in the shop", type: "checkbox" },
  ] },
  orders: { title: "Shop orders", subtitle: "Kit bookings placed by fans. Confirm the order after you agree payment and delivery.", edit: true, columns: [["number", "ORDER"], ["name", "FAN"], ["phone", "PHONE"], ["email", "EMAIL"], ["total", "TOTAL"], ["status", "STATUS"]], fields: [{ key: "status", label: "Order status", type: "select", options: ["PENDING", "CONFIRMED", "CANCELLED"], required: true }] },
  polls: { title: "Polls", subtitle: "Questions fans answer with their name, email and phone.", create: true, edit: true, remove: true, columns: [["title", "POLL"], ["optionCount", "CHOICES"], ["voteCount", "VOTES"], ["isPublished", "LIVE"]], fields: [
    { key: "title", label: "Poll title", required: true }, { key: "question", label: "Question", required: true }, { key: "description", label: "Introduction", type: "textarea" }, { key: "closesAt", label: "Closes", type: "date", hint: "Leave blank to keep the poll open." }, { key: "isPublished", label: "Show on the website", type: "checkbox" },
  ] },
  contests: { title: "Contests", subtitle: "Fan competitions. Each person enters once with their contact details.", create: true, edit: true, remove: true, columns: [["title", "CONTEST"], ["prize", "PRIZE"], ["entryCount", "ENTRIES"], ["isPublished", "LIVE"]], fields: [
    { key: "title", label: "Contest title", required: true }, { key: "prize", label: "Prize" }, { key: "prompt", label: "What should fans answer?", required: true, hint: "Shown above the entry box." }, { key: "description", label: "Description", type: "textarea", required: true }, { key: "image", label: "Image", type: "file", accept: "image/jpeg,image/png,image/webp" }, { key: "closesAt", label: "Closes", type: "date" }, { key: "isPublished", label: "Show on the website", type: "checkbox" },
  ] },
  contacts: { title: "Contact messages", subtitle: "Review supporter, partnership and media enquiries.", columns: [["name", "SENDER"], ["email", "EMAIL"], ["subject", "SUBJECT"], ["isRead", "STATUS"], ["createdAt", "RECEIVED"]] },
  records: { title: "Statistics & records", subtitle: "Record cards shown on the website. Match totals still come from scorecards.", create: true, edit: true, remove: true, columns: [["title", "RECORD"], ["value", "VALUE"], ["scope", "SCOPE"], ["playerName", "PLAYER"], ["seasonYear", "SEASON"]], fields: [
    { key: "title", label: "Record name", required: true, hint: "Shown as the card heading, for example Highest individual score." },
    { key: "value", label: "Value", required: true, hint: "The figure on the card, for example 61 or 3/19." },
    { key: "category", label: "Category", required: true, hint: "Shown beside the scope, for example BATTING or TEAM." },
    { key: "scope", label: "Scope", required: true, hint: "Shown on the card, for example SEASON or LIFETIME." },
    { key: "playerName", label: "Player or team name", hint: "Shown under the record. Leave blank to show United Tigers." },
    { key: "seasonYear", label: "Season", type: "number", hint: "Shown after the player name, for example 2026." },
  ] },
  settings: { title: "Website settings", subtitle: "Homepage copy and any extra public settings. Site URL, live scores and storage are saved in the form above.", create: true, columns: [["key", "SETTING"], ["value", "VALUE"], ["updatedAt", "UPDATED"]], fields: [{ key: "key", label: "Setting key", required: true }, { key: "value", label: "Value (plain text or JSON)", type: "textarea", required: true }] },
  audit: { title: "Audit log", subtitle: "A traceable history of important administrator actions.", columns: [["action", "ACTION"], ["entity", "SECTION"], ["entityId", "RECORD"], ["user", "ADMIN"], ["createdAt", "TIME"]] },
  users: { title: "Admin users", subtitle: "Create administrator accounts and assign a built-in access role.", create: true, edit: true, remove: true, columns: [["name", "NAME"], ["email", "EMAIL"], ["role", "ROLE"], ["isActive", "ACTIVE"], ["lastLoginAt", "LAST SIGN-IN"]], fields: [{ key: "name", label: "Full name", required: true }, { key: "email", label: "Email address", type: "text", required: true }, { key: "role", label: "Access role", type: "select", options: ["SUPER_ADMIN", "ADMIN", "EDITOR", "STATISTICS_MANAGER", "CONTENT_MANAGER"], required: true }, { key: "password", label: "Temporary password", type: "password", required: true, hint: "At least 12 characters. Leave blank when editing to keep the current password." }, { key: "isActive", label: "Active account", type: "checkbox" }] },
  roles: { title: "Roles & permissions", subtitle: "Built-in roles use a fixed permission matrix enforced by every API route.", columns: [["name", "ROLE"], ["description", "ACCESS SUMMARY"], ["permissions", "PERMISSIONS"]] },
};
const managedSettingKeys = new Set(["siteUrl", "livePollIntervalMs", "storage", "homepage", "smtp"]);
const showValue = (value: unknown) => value == null || value === "" ? "—" : typeof value === "boolean" ? value ? "YES" : "NO" : typeof value === "object" ? JSON.stringify(value) : String(value);
const recordName = (item: Entry) => String(item.number ?? item.title ?? item.fullName ?? item.name ?? item.opponent ?? item.key ?? "this record");

export function AdminWorkspace({ section }: { section: string }) {
  const definition = adminSections[section]; const [items, setItems] = useState<Entry[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [pending, setPending] = useState<Entry | null>(null); const [deleting, setDeleting] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true);
    try { const response = await fetch(`/api/v1/admin/${section}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Could not load this section."); setItems(Array.isArray(result.data) ? result.data : []); if (result.message?.includes("Database is not connected")) setError(result.message); else setError(""); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load this section."); setItems([]); } finally { setLoading(false); }
  }, [section]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => items.filter((item) => (section !== "settings" || !managedSettingKeys.has(String(item.key))) && JSON.stringify(item).toLowerCase().includes(query.toLowerCase())), [items, query, section]);
  if (!definition) return <div className="admin-content"><div className="admin-page-heading"><div><h1>Section unavailable</h1><p>This CMS section doesn’t exist.</p></div></div></div>;
  async function confirmDelete() {
    if (!pending) return;
    setDeleting(true); setError(""); setNotice("");
    try { const response = await fetch(`/api/v1/admin/${section}/${pending.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Could not delete this record."); setNotice("Record deleted."); setPending(null); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not delete this record."); setPending(null); }
    finally { setDeleting(false); }
  }
  async function markRead(item: Entry) { try { const response = await fetch(`/api/v1/admin/${section}/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ isRead: true }) }); if (!response.ok) throw new Error("Could not mark message as read."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update message."); } }
  return <div className="admin-content"><div className="admin-page-heading"><div><span className="eyebrow"><i className="eyebrow-dot" />UNITED TIGERS CMS</span><h1>{definition.title}</h1><p>{definition.subtitle}</p></div><button className="admin-secondary-btn" onClick={() => void load()}><RefreshCw size={13} /> Refresh</button></div>
    {section === "settings" && <SiteSettingsPanel />}
    {error && <div className="admin-demo-alert"><AlertTriangle size={14} />{error}</div>}{notice && <p className="admin-notice"><Check size={13} /> {notice}</p>}
    <div className="admin-toolbar"><label className="admin-search-wrap"><Search size={14} /><input className="admin-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${definition.title.toLowerCase()}`} /></label>{definition.create && <Link className="admin-primary-btn" href={`/admin/${section}/new`}><Plus size={14} /> Create new</Link>}</div>
    {loading ? <div className="admin-table-wrap"><div className="admin-loading-inline"><span className="admin-spinner" /> LOADING RECORDS</div></div> : visible.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{definition.columns.map(([key, label]) => <th key={key}>{label}</th>)}{(definition.edit || definition.remove || section === "contacts" || section === "matches") && <th>ACTIONS</th>}</tr></thead><tbody>{visible.map((item) => <tr key={item.id}>{definition.columns.map(([key]) => <td key={key}><strong>{key === "user" ? String((item.user as { email?: string } | null)?.email || "Admin") : key === "venue" ? String((item.venue as { name?: string } | null)?.name || "—") : showValue(item[key])}</strong></td>)}{(definition.edit || definition.remove || section === "contacts" || section === "matches") && <td className="row-actions">{section === "matches" && <Link href={`/admin/matches/${item.id}/scorecard`}>SCORECARD</Link>}{definition.edit && <Link href={`/admin/${section}/${item.id}`}><Edit3 size={12} /> Edit</Link>}{section === "contacts" && !item.isRead && <button onClick={() => void markRead(item)}><Check size={12} /> Mark read</button>}{definition.remove && <button className="danger-text" onClick={() => setPending(item)}><Trash2 size={12} /> Delete</button>}</td>}</tr>)}</tbody></table></div> : !error ? <EmptyState title={query ? "No matching records" : "Nothing here yet"} description={query ? "Adjust the search and try again." : "New records will appear here when added through the CMS."} /> : null}
    {section === "gallery" && <p className="admin-storage-note">Uploads use the S3-compatible storage saved in Site settings. Add the endpoint, bucket and keys there before uploading media.</p>}
    {pending && <div className="admin-confirm" role="presentation" onClick={() => { if (!deleting) setPending(null); }}><div className="admin-confirm-card" role="dialog" aria-modal="true" aria-labelledby="delete-title" onClick={(event) => event.stopPropagation()}><h2 id="delete-title">Delete this record?</h2><p>Delete “{recordName(pending)}” permanently. It will be removed from the CMS and the website.</p><div className="admin-confirm-actions"><button type="button" className="admin-secondary-btn" disabled={deleting} onClick={() => setPending(null)}>Cancel</button><button type="button" className="admin-danger-btn" disabled={deleting} onClick={() => void confirmDelete()}>{deleting ? "Deleting…" : "Delete"}</button></div></div></div>}
  </div>;
}

