"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Check, Plus, Save, Trash2 } from "lucide-react";

type Player = { id: string; fullName: string };
type Line = { playerId: string; runs: string; balls: string; fours: string; sixes: string; dismissal: string; overs: string; maidens: string; wickets: string; runsConceded: string; wides: string; noBalls: string };
type InningsRow = { number: number; battingTeam: string; runs: string; wickets: string; overs: string; batting: Line[]; bowling: Line[] };
type FieldingRow = { playerId: string; catches: string; runOuts: string; stumpings: string };
type LiveStateForm = { innings: string; runs: string; wickets: string; overs: string; currentBatsmen: string; currentBowler: string; partnership: string; currentRunRate: string; requiredRunRate: string; latestEvent: string };
const blankLiveState = (): LiveStateForm => ({ innings: "1", runs: "", wickets: "", overs: "", currentBatsmen: "", currentBowler: "", partnership: "", currentRunRate: "", requiredRunRate: "", latestEvent: "" });
const blankLine = (): Line => ({ playerId: "", runs: "0", balls: "0", fours: "0", sixes: "0", dismissal: "", overs: "0.0", maidens: "0", wickets: "0", runsConceded: "0", wides: "0", noBalls: "0" });
const blankInnings = (number: number, team: string): InningsRow => ({ number, battingTeam: team, runs: "0", wickets: "0", overs: "0.0", batting: [blankLine()], bowling: [blankLine()] });
const number = (value: unknown, fallback = "0") => value == null ? fallback : String(value);

export function ScorecardEditor({ id }: { id: string }) {
  const router = useRouter(); const [match, setMatch] = useState<Record<string, unknown> | null>(null); const [players, setPlayers] = useState<Player[]>([]); const [innings, setInnings] = useState<InningsRow[]>([]); const [fielding, setFielding] = useState<FieldingRow[]>([ { playerId: "", catches: "0", runOuts: "0", stumpings: "0" } ]); const [result, setResult] = useState(""); const [status, setStatus] = useState("UPCOMING"); const [liveState, setLiveState] = useState<LiveStateForm>(blankLiveState()); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { fetch(`/api/v1/admin/matches/${id}/scorecard`, { cache: "no-store" }).then((response) => response.json().then((data) => ({ response, data }))).then(({ response, data }) => {
    if (!response.ok) throw new Error(data.message || "Could not load the match.");
    const record = data.data.match as Record<string, unknown> & { innings: Record<string, unknown>[]; fielding: Record<string, unknown>[] };
    const roster = data.data.players as Player[]; setMatch(record); setPlayers(roster); setResult(String(record.result || "")); setStatus(String(record.status || "UPCOMING"));
    const savedLive = (record.liveState && typeof record.liveState === "object" ? record.liveState : {}) as Record<string, unknown>; setLiveState({ innings: number(savedLive.innings, "1"), runs: number(savedLive.runs, ""), wickets: number(savedLive.wickets, ""), overs: number(savedLive.overs, ""), currentBatsmen: Array.isArray(savedLive.currentBatsmen) ? savedLive.currentBatsmen.join(", ") : "", currentBowler: String(savedLive.currentBowler || ""), partnership: String(savedLive.partnership || ""), currentRunRate: number(savedLive.currentRunRate, ""), requiredRunRate: number(savedLive.requiredRunRate, ""), latestEvent: String(savedLive.latestEvent || "") });
    const rows = record.innings.map((entry) => ({ number: Number(entry.number), battingTeam: String(entry.battingTeam), runs: number(entry.runs), wickets: number(entry.wickets), overs: number(entry.overs, "0.0"), batting: (entry.batting as Record<string, unknown>[]).map((line) => ({ ...blankLine(), playerId: String(line.playerId), runs: number(line.runs), balls: number(line.balls), fours: number(line.fours), sixes: number(line.sixes), dismissal: String(line.dismissal || "") })), bowling: (entry.bowling as Record<string, unknown>[]).map((line) => ({ ...blankLine(), playerId: String(line.playerId), overs: number(line.overs, "0.0"), maidens: number(line.maidens), runsConceded: number(line.runs), wickets: number(line.wickets), wides: number(line.wides), noBalls: number(line.noBalls) })) }));
    setInnings(rows.length ? rows : [blankInnings(1, "United Tigers"), blankInnings(2, String(record.opponent))]);
    const fieldRows = record.fielding.map((line) => ({ playerId: String(line.playerId), catches: number(line.catches), runOuts: number(line.runOuts), stumpings: number(line.stumpings) })); setFielding(fieldRows.length ? fieldRows : [{ playerId: "", catches: "0", runOuts: "0", stumpings: "0" }]);
  }).catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load scorecard.")); }, [id]);
  function updateInnings(index: number, key: keyof InningsRow, value: string) { setInnings((rows) => rows.map((row, i) => i === index ? { ...row, [key]: value } : row)); }
  function updateLine(index: number, group: "batting" | "bowling", lineIndex: number, key: keyof Line, value: string) { setInnings((rows) => rows.map((row, i) => i === index ? { ...row, [group]: row[group].map((line, j) => j === lineIndex ? { ...line, [key]: value } : line) } : row)); }
  function updateField(index: number, key: keyof FieldingRow, value: string) { setFielding((rows) => rows.map((row, i) => i === index ? { ...row, [key]: value } : row)); }
  async function save() {
    setBusy(true); setError(""); setNotice("");
    const body = { result: result || null, status, liveState: status === "LIVE" ? { innings: Number(liveState.innings || 1), ...(liveState.runs !== "" ? { runs: Number(liveState.runs) } : {}), ...(liveState.wickets !== "" ? { wickets: Number(liveState.wickets) } : {}), ...(liveState.overs !== "" ? { overs: liveState.overs } : {}), currentBatsmen: liveState.currentBatsmen.split(",").map((name) => name.trim()).filter(Boolean), ...(liveState.currentBowler ? { currentBowler: liveState.currentBowler } : {}), ...(liveState.partnership ? { partnership: liveState.partnership } : {}), ...(liveState.currentRunRate !== "" ? { currentRunRate: Number(liveState.currentRunRate) } : {}), ...(liveState.requiredRunRate !== "" ? { requiredRunRate: Number(liveState.requiredRunRate) } : {}), ...(liveState.latestEvent ? { latestEvent: liveState.latestEvent } : {}) } : null, innings: innings.map((entry) => ({ number: entry.number, battingTeam: entry.battingTeam, runs: Number(entry.runs), wickets: Number(entry.wickets), overs: Number(entry.overs), batting: entry.batting.map((line) => ({ playerId: line.playerId || undefined, runs: Number(line.runs), balls: Number(line.balls), fours: Number(line.fours), sixes: Number(line.sixes), dismissal: line.dismissal || null })), bowling: entry.bowling.map((line) => ({ playerId: line.playerId || undefined, overs: Number(line.overs), maidens: Number(line.maidens), runs: Number(line.runsConceded), wickets: Number(line.wickets), wides: Number(line.wides), noBalls: Number(line.noBalls) })) })), fielding: fielding.filter((line) => line.playerId).map((line) => ({ playerId: line.playerId, catches: Number(line.catches), runOuts: Number(line.runOuts), stumpings: Number(line.stumpings) })) };
    try { const response = await fetch(`/api/v1/admin/matches/${id}/scorecard`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Scorecard could not be saved."); setNotice("Scorecard saved. Player and season statistics are recalculated from this match."); router.refresh(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Scorecard could not be saved."); } finally { setBusy(false); }
  }
  if (!match) return <div className="admin-content"><div className="admin-loading-inline">LOADING MATCH</div>{error && <div className="admin-demo-alert">{error}</div>}</div>;
  return <div className="admin-content"><div className="admin-page-heading"><div><Link className="admin-back" href="/admin/matches"><ArrowLeft size={13} /> FIXTURES & MATCHES</Link><span className="eyebrow"><i className="eyebrow-dot" />STATISTICS EDITOR</span><h1>Match scorecard</h1><p>United Tigers vs {String(match.opponent)} · {new Date(String(match.date)).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}</p></div><button className="admin-primary-btn" onClick={() => void save()} disabled={busy}><Save size={14} />{busy ? "SAVING…" : "SAVE SCORECARD"}</button></div>
    <div className="scorecard-admin-controls"><label>Match status<select value={status} onChange={(event) => setStatus(event.target.value)}>{["UPCOMING", "LIVE", "COMPLETED", "POSTPONED", "CANCELLED"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Result<input value={result} onChange={(event) => setResult(event.target.value)} placeholder="United Tigers won by …" /></label></div>
    {status === "LIVE" && <section className="admin-scorecard-innings live-admin-editor"><header><div><span className="eyebrow">LIVE SCORE CONTROL</span><h2>Match centre feed</h2></div></header><div className="admin-editor-grid">{([ ["innings", "Innings"], ["runs", "Runs"], ["wickets", "Wickets"], ["overs", "Overs (cricket notation)"], ["currentBatsmen", "Batters at crease (comma separated)"], ["currentBowler", "Current bowler"], ["partnership", "Partnership"], ["currentRunRate", "Current run rate"], ["requiredRunRate", "Required run rate"], ["latestEvent", "Latest event"] ] as [keyof LiveStateForm, string][]).map(([key, label]) => <label key={key}>{label}<input type={key === "currentBatsmen" || key === "currentBowler" || key === "partnership" || key === "latestEvent" ? "text" : key === "overs" ? "text" : "number"} min={key === "currentRunRate" || key === "requiredRunRate" ? "0" : undefined} step={key === "currentRunRate" || key === "requiredRunRate" ? "0.01" : "1"} value={liveState[key]} onChange={(event) => setLiveState((current) => ({ ...current, [key]: event.target.value }))} /></label>)}</div></section>}
    {error && <div className="admin-demo-alert">{error}</div>}{notice && <p className="admin-notice"><Check size={13} /> {notice}</p>}
    {innings.map((entry, index) => <section className="admin-scorecard-innings" key={entry.number}><header><div><span className="eyebrow">INNINGS {entry.number}</span><h2>Score summary</h2></div><button className="admin-secondary-btn" onClick={() => setInnings((rows) => rows.filter((_, i) => i !== index))}><Trash2 size={13} /> Remove</button></header><div className="admin-editor-grid"><label>Batting team<input value={entry.battingTeam} onChange={(event) => updateInnings(index, "battingTeam", event.target.value)} /></label><label>Runs<input type="number" min="0" value={entry.runs} onChange={(event) => updateInnings(index, "runs", event.target.value)} /></label><label>Wickets<input type="number" min="0" max="10" value={entry.wickets} onChange={(event) => updateInnings(index, "wickets", event.target.value)} /></label><label>Overs (cricket notation)<input type="number" min="0" max="10" step="0.1" value={entry.overs} onChange={(event) => updateInnings(index, "overs", event.target.value)} /></label></div>
      <div className="scorecard-admin-subsection"><div className="admin-panel-header"><h3>Batting performance</h3><button className="admin-secondary-btn" onClick={() => setInnings((rows) => rows.map((row, i) => i === index ? { ...row, batting: [...row.batting, blankLine()] } : row))}><Plus size={12} /> ADD BATTER</button></div><div className="scorecard-lines">{entry.batting.map((line, lineIndex) => <div className="scorecard-line" key={lineIndex}><select aria-label="Batter" value={line.playerId} onChange={(event) => updateLine(index, "batting", lineIndex, "playerId", event.target.value)}><option value="">Select player</option>{players.map((player) => <option value={player.id} key={player.id}>{player.fullName}</option>)}</select>{([["runs", "R"], ["balls", "B"], ["fours", "4s"], ["sixes", "6s"]] as [keyof Line, string][]).map(([key, label]) => <label key={key}>{label}<input type="number" min="0" value={line[key]} onChange={(event) => updateLine(index, "batting", lineIndex, key, event.target.value)} /></label>)}<input className="dismissal-input" aria-label="Dismissal" value={line.dismissal} onChange={(event) => updateLine(index, "batting", lineIndex, "dismissal", event.target.value)} placeholder="Dismissal / not out" /><button aria-label="Remove batter" className="line-remove" onClick={() => setInnings((rows) => rows.map((row, i) => i === index ? { ...row, batting: row.batting.filter((_, j) => j !== lineIndex) } : row))}><Trash2 size={12} /></button></div>)}</div></div>
      <div className="scorecard-admin-subsection"><div className="admin-panel-header"><h3>Bowling performance</h3><button className="admin-secondary-btn" onClick={() => setInnings((rows) => rows.map((row, i) => i === index ? { ...row, bowling: [...row.bowling, blankLine()] } : row))}><Plus size={12} /> ADD BOWLER</button></div><div className="scorecard-lines">{entry.bowling.map((line, lineIndex) => <div className="scorecard-line" key={lineIndex}><select aria-label="Bowler" value={line.playerId} onChange={(event) => updateLine(index, "bowling", lineIndex, "playerId", event.target.value)}><option value="">Select player</option>{players.map((player) => <option value={player.id} key={player.id}>{player.fullName}</option>)}</select>{([["overs", "O"], ["maidens", "M"], ["runsConceded", "R"], ["wickets", "W"], ["wides", "Wd"], ["noBalls", "Nb"]] as [keyof Line, string][]).map(([key, label]) => <label key={key}>{label}<input type="number" min="0" step={key === "overs" ? "0.1" : "1"} value={line[key]} onChange={(event) => updateLine(index, "bowling", lineIndex, key, event.target.value)} /></label>)}<button aria-label="Remove bowler" className="line-remove" onClick={() => setInnings((rows) => rows.map((row, i) => i === index ? { ...row, bowling: row.bowling.filter((_, j) => j !== lineIndex) } : row))}><Trash2 size={12} /></button></div>)}</div></div>
    </section>)}
    {innings.length < 2 && <button className="admin-secondary-btn add-innings" onClick={() => setInnings((rows) => [...rows, blankInnings(2, String(match.opponent))])}><Plus size={14} /> ADD SECOND INNINGS</button>}
    <section className="admin-scorecard-innings"><header><div><span className="eyebrow">FIELDING</span><h2>Catches, run outs & stumpings</h2></div><button className="admin-secondary-btn" onClick={() => setFielding((rows) => [...rows, { playerId: "", catches: "0", runOuts: "0", stumpings: "0" }])}><Plus size={12} /> ADD FIELDER</button></header><div className="scorecard-lines">{fielding.map((line, index) => <div className="scorecard-line" key={index}><select aria-label="Fielder" value={line.playerId} onChange={(event) => updateField(index, "playerId", event.target.value)}><option value="">Select player</option>{players.map((player) => <option key={player.id} value={player.id}>{player.fullName}</option>)}</select>{([["catches", "Catches"], ["runOuts", "Run outs"], ["stumpings", "Stumpings"]] as [keyof FieldingRow, string][]).map(([key, label]) => <label key={key}>{label}<input type="number" min="0" value={line[key]} onChange={(event) => updateField(index, key, event.target.value)} /></label>)}</div>)}</div></section>
    <div className="scorecard-save-bottom"><span>All rate fields are calculated from the innings data.</span><button className="admin-primary-btn" onClick={() => void save()} disabled={busy}><Save size={14} />{busy ? "SAVING…" : "SAVE SCORECARD"}</button></div>
  </div>;
}

